name: build and release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: ""
            archive_ext: tar.gz
          - os: ubuntu-latest
            rid: linux-arm64
            ext: ""
            archive_ext: tar.gz
          - os: macos-latest
            rid: osx-x64
            ext: ""
            archive_ext: tar.gz
          - os: macos-latest
            rid: osx-arm64
            ext: ""
            archive_ext: tar.gz
          - os: windows-latest
            rid: win-x64
            ext: ".exe"
            archive_ext: zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish binary
        run: |
          dotnet publish src/Tsk.CLI/Tsk.CLI.csproj \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:IncludeNativeLibrariesForSelfExtract=true \
            /p:EnableCompressionInSingleFile=true \
            /p:DebugType=none \
            -o publish

      - name: Rename binary
        run: mv publish/Tsk.CLI${{ matrix.ext }} tsk-${{ matrix.rid }}${{ matrix.ext }}

      - name: Compress binary (Unix)
        if: runner.os != 'Windows'
        run: |
          tar -czvf tsk-${{ matrix.rid }}.${{ matrix.archive_ext }} tsk-${{ matrix.rid }}

      - name: Compress binary (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell Compress-Archive -Path tsk-${{ matrix.rid }}.exe -DestinationPath tsk-${{ matrix.rid }}.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: tsk-${{ matrix.rid }}.${{ matrix.archive_ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
